### ISSUE TITLE
I can't find some files in your code: enzyme_data/PCA_Unirep.pkl etc.

### ISSUE THREAD

**Issue by CallMeDek** [AlexanderKroll/KM_prediction#4]
Hi, 

I am following your codes according to Jupyter files in notebooks_and_code.

As I followed the line, I found out there was a problem.

I was not able to find some files written in your code, functions_for_data_preprocessing.py

Any tips for this?

Thanks.

**Comment by AlexanderKroll** [comment]
Hi Dek,

Did you change in "KM_prediction/notebooks_and_code/directory_infomation.py" the path pointing to all datasets? In directory_information.py you have to set datasets_dir = "Path_to_github_repository\\KM_prediction\\datasets\\"? 
If you have already done this, please let me know which files are missing.

Best,
Alex

**Comment by CallMeDek** [comment]
Hi,

I already changed the path pointing to datasets in directory_information.py.

I got an error below:
```
FileNotFoundError                         Traceback (most recent call last)
Input In [16], in <module>
     19 warnings.filterwarnings('ignore')
     21 from directory_infomation import *
---> 22 from additional_code.functions_for_data_preprocessing import *

File /data2/dek_data/KM_prediction/notebooks_and_code/additional_code/functions_for_data_preprocessing.py:482, in <module>
    478     df = df.loc[df["log10_KM"]< 4]
    480     return(df)
--> 482 pca = pickle.load(open(join(datasets_dir, "enzyme_data", "PCA_Unirep.pkl"),'rb'))
    483 mean = np.load(join(datasets_dir, "enzyme_data", "mean_PCA_Unirep.npy"))
    484 std = np.load(join(datasets_dir, "enzyme_data", "std_PCA_Unirep.npy"))

FileNotFoundError: [Errno 2] No such file or directory: '/home/dek/data2/KM_prediction/datasets/enzyme_data/PCA_Unirep.pkl'
```

Based on the code in functions_for_data_preprocessing.py, you loaded PCA_Unirep.pkl in enzyme_data 
but I can't see even that folder in datasets. 

Could you tell me where those files?
(datasets/enzyme_data/PCA_Unirep.pkl, datasets/enzyme_data/mean_PCA_Unirep.npy, datasets/enzyme_data/std_PCA_Unirep.npy)

Thank you

**Comment by AlexanderKroll** [comment]
Hi, 

for some reason I didn't upload the folders "KM_prediction/datasets/enzyme_data/" and "KM_prediction/datasets/substrate_synonyms/". I am sorry for that! I have just uploaded those two folders to the repositiry. I hope nothing else is missing. Please let me know if you face any other issues.

Best,
Alex

**Comment by CallMeDek** [comment]
Hi, AlexanderKroll

Thanks for your help.
Unfortunately, I ran into another issue like below.
```
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
Input In [1], in <module>
     19 warnings.filterwarnings('ignore')
     21 from directory_infomation import *
---> 22 from functions_for_data_preprocessing import *

File /data2/dek_data/KM_prediction/notebooks_and_code/./additional_code/functions_for_data_preprocessing.py:482, in <module>
    478     df = df.loc[df["log10_KM"]< 4]
    480     return(df)
--> 482 pca = pickle.load(open(join(datasets_dir, "enzyme_data", "PCA_Unirep.pkl"),'rb'))
    483 mean = np.load(join(datasets_dir, "enzyme_data", "mean_PCA_Unirep.npy"))
    484 std = np.load(join(datasets_dir, "enzyme_data", "std_PCA_Unirep.npy"))

UnpicklingError: invalid load key, 'v'.
```

It seems that you downloaded Unirep file by Git LFS  according to PCA_Unirep.pkl.
I guess it was because the file was large. 
But I am not able to understand how it works.
Could you let me know about it , please?

Regards, 
Dek

**Comment by CallMeDek** [comment]
Ok, I found out how I can resolve the problem. 
In my opinion, you should mention two things more in user guide line. 
1) Installation of ete3: you call ete3 libraray in functions_for_data_preprocessing.py
2) Before cloning this repo, you have to install git lfs first and then pull like below:
    [1] Install git lfs
    [2] git clone this repo
    [3] git lfs pull
It works for me.
Anyway, I appreciate your help

Regards,
Dek
